name: Documentation

on:
  pull_request:
    types: [ closed ]
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy-doc:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Recup code depot
        uses: actions/checkout@v4

      - name: Config jdk21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Generation de la Javadoc
        run: |
          mvn -B javadoc:javadoc
          if [ -d "target/reports/apidocs" ] && [ ! -d "target/site/apidocs" ]; then
            mkdir -p target/site
            cp -r target/reports/apidocs target/site/apidocs
          fi

      - name: Deploiement GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
